### ISSUE TITLE
How Can i run eth-indedxer with a mysql outsite the docker?

### ISSUE THREAD

**Issue by bestony** [getamis/eth-indexer#79]
My host have a mysql .

How can i run  eth-indexer without create a new mysql container?

**Comment by shad0356jc** [comment]
Just remove the mysql part of `docker-compose.yml`.

**Comment by bestony** [comment]
if i remove mysql part ,how should i set  database for eth-indexer?

maybe you can give a guide.

**Comment by tailingchen** [comment]
@bestony You can set your database host and port in [config.yaml](https://github.com/getamis/eth-indexer/blob/develop/configs/config.yaml). The default values of flags is from config file.
