### ISSUE TITLE
Failed to get total supply   err="no contract code at given address"

### ISSUE THREAD

**Issue by faithgithub** [getamis/eth-indexer#81]
Hi when I start the docker：
I got "no contract code at given address"。my erc20 config do not change
![image](https://user-images.githubusercontent.com/6094902/44143723-57ff1b78-a0b7-11e8-9fbe-3ad1b5611a02.png)

**doker-compose.yaml**

version: "3"
services:
  # Customized geth image for indexer
  geth:
    image: quay.io/amis/geth:indexer_diff_tx_1.8.10
    ports:
      - "30303:30303"
      - "8546:8546"
    volumes:
      - ${GETH_DATA_PATH}:/root/.ethereum
    command: "--gcmode=archive --syncmode=full --wsapi \"eth,debug\" --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins \"*\""
    restart: always
    depends_on:
      - idx-database
    links:
      - idx-database
  idx-database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=qwe!@#123
      - MYSQL_CHARSET=utf8
      - MYSQL_DATABASE=ethdb
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
  idx-migration:
    build:
      context: ./migration
    command: ["rake", "db:migrate"]
    restart: on-failure
    depends_on:
      - idx-database
    environment:
      - RAILS_ENV=customized
      - HOST=idx-database
      - PORT=3306
      - DATABASE=ethdb
      - USERNAME=root
      - PASSWORD=qwe!@#123
  indexer:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    command:
      - indexer
    restart: on-failure
    depends_on:
      - idx-database
      - idx-migration
      - geth
    links:
      - idx-database:db
      - geth:eth
    volumes:
      - ./configs:/configs

**config.yaml**

eth:
  protocol: ws
  host: geth
  port: 8546
db:
  driver: mysql
  host: idx-database
  port: 3306
  name: ethdb
  user: root
  password: qwe!@#123
sync:
  fromBlock: 0
pprof:
  enable: false
  port: 8000
  address: "0.0.0.0"
functions:
  erc20token: true
chain:
  test: false

**erc20.yaml**

erc20:
  usdt:
    address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
  eos:
    address: "0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0"
  trx:
    address: "0xf230b790e05390fc8295f4d3f60332c93bed42e2"
  ven:
    address: "0xd850942ef8811f2a866692a623011bde52a462c1"

**Comment by shad0356jc** [comment]
Hi @faithgithub 
Problem is that your geth needs some time to sync to the block where ERC20 contract was created.
From the screenshot you provided, latest block of your geth is `2323698` which is far from the block `4634748` where USDT was created. Therefore indexer is not able to find contract code from geth.
